# Generated by Django 5.1.4 on 2026-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('counseling_date', models.DateField()),
                ('counseling_type', models.CharField(choices=[('Spiritual', 'Spiritual Counseling'), ('Family', 'Family Counseling'), ('Youth', 'Youth Counseling'), ('Prayer', 'Prayer Counseling'), ('Marriage', 'Marriage Counseling'), ('Student', 'Student Counseling')], max_length=50)),
                ('counselor_preference', models.CharField(choices=[('Female', 'Female Counselor'), ('Male', 'Male Counselor'), ('Anyone', 'Anyone Available')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
