# Generated by Django 5.1.4 on 2026-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('counseling_type', models.CharField(max_length=50)),
                ('counselor', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CounselingBooking',
        ),
    ]
