# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_user', '0002_counselbooking_delete_counselingbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
