# Generated by Django 5.1.4 on 2026-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_user', '0004_userprayerrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselbooking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.AlterField(
            model_name='counselbooking',
            name='counseling_type',
            field=models.CharField(choices=[('family', 'Family Counselling'), ('marriage', 'Marriage Counselling'), ('education', 'Educational Counselling'), ('mental', 'Mental Health Counselling'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='counselbooking',
            name='counselor',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=20),
        ),
        migrations.AlterField(
            model_name='counselbooking',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
