# Generated by Django 5.1.4 on 2025-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_admin', '0002_galleryimage_galleryvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
