# Generated by Django 5.1.4 on 2025-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_admin', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='video',
            field=models.FileField(upload_to='gallery_videos/'),
        ),
    ]
