# Generated by Django 5.1.4 on 2026-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_admin', '0004_alter_galleryimage_image_alter_galleryvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
