# Generated by Django 5.1.4 on 2026-03-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuva_admin', '0005_missionary'),
        ('vuva_missionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='missionary_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuva_admin.missionary')),
            ],
        ),
    ]
